apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-couh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-couh
    app.kubernetes.io/part-of: test-app-gffm
  name: test-component-couh
  namespace: build-e2e-xoxv-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-couh
status:
  loadBalancer: {}
